# Файл docker-compose должен начинаться с указания версии.
version: '3'

# Сети
networks:
  internal:

# Ниже список наших сервисов (контейнеров). NGINX, PHP, MySQL, Redis
services:
  nginx:
    # Какую версию образа nginx из официального хранилища DockerHub используем
    image: nginx:stable-alpine
    container_name: nginx
    # Ниже прокидываем порты+
    ports:
      - "8080:80"
    # Монтируем директории, слева директории на основной системе, справа - куда они монтируются в контейнере
    volumes:
      - ./src:/var/www
      - ./config/nginx:/etc/nginx/conf.d
      - ./data/logs:/var/log/nginx/
    # Зависимости
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - internal
  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile
    container_name: php
    links:
      - mysql
      - redis
    volumes:
      - ./src:/var/www
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    ports:
      - "9000:9000"
    networks:
      - internal
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    command: --innodb_use_native_aio=0
    ports:
      - "33060:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    # Задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - internal
  redis:
    image: redis:4.0
    container_name: redis_do
    ports:
      - "63790:6379"
    volumes:
        - ./data/redis:/data
    networks:
      - internal